package com.control.chickenapp.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.control.chickenapp.entity.User;
import com.control.chickenapp.service.UserProfileService;

@Controller
public class UserController {
  @Autowired // This means to get the bean called userRepository
//         // Which is auto-generated by Spring, we will use it to handle the data
  private UserProfileService userProfileService;

//
  @GetMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser () {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

	User n = new User();
    n.setMobileNo("81659347");
    n.setPassword("Welcome@01");
    boolean isAdded = userProfileService.addUser(n);
    if(isAdded) {
    	System.out.println("User added successfully");
    }else {
    	System.out.println("User addition failed!!!!");
    }
    return "User registered successfully";
  }
//
//  @GetMapping(path="/all")
//  public @ResponseBody Iterable<UserProfile> getAllUsers() {
//    // This returns a JSON or XML with the users
//    return userRepository.findAll();
//  }
}